### ISSUE TITLE
Custom header params

### ISSUE THREAD

**Issue by sanjayradadiya** [theo4u/sails-hook-swagger-generator#45]
Hi,

I am trying to add custom header params like tokens but as per documentation it is not properly generated.

Is it possible to generate global params for all endpoint as token are doing without adding ref in all endpoints ?

**Comment by theo4u** [comment]
currently, no way to set global parameter refs.  I'm trying to imagine the use case because not all route might want to use the ref,  instead, it's rather something like so: 
`ref:  Array<endpoint that needs the ref>`

which I think is the same work as adding it to each of the routes. 

Will leave this open in case anybody is looking for this same feature.

**Comment by sanjayradadiya** [comment]
Can you post example here for better understanding ?

**Comment by theo4u** [comment]
yeah, 

open your `config/swaggergenerator.js` 

then add the new ref to `parameters` as specified here: https://github.com/theo4u/sails-hook-swagger-generator#configurations

yours can be

```js
 CustomParamName: {
            in: 'query', // which can also be path, etc
            name: 'customName',
            required: false,
            type: 'integer',
            description: 'custom descript'
        }
```

Then to use in your route do this

```js
'post /user/login': {
    controller: 'UserController',
    action: 'login',
    swagger: {
      // other configuration fields here ...
      query: [{
        $ref: '#/parameters/CustomParamName' // ===> see here the way it was called
      }],
      parameters: [{
        in: 'query',
        name: 'firstName',
        required: true,
        type: 'string',
        description: 'This is a custom required parameter'
      }] // or use this to create a new one just for this route
    }
  }
```

**Comment by theo4u** [comment]
Hope it makes sense @sanjayradadiya?

**Comment by sanjayradadiya** [comment]
Hi,

I think still something is not getting as aspected 

see my parameter is 

```
      KeyHeaderParam: {
          in: 'header',
          name: 'key',
          required: true,
          type: 'string',
          description: 'API key for identifications for each stores',
        },
```

and i have try to add ref in routes but its generates in wrong format as attache in image.

https://prnt.sc/nk0dak

but it should be generate something like this as similar to token 

https://prnt.sc/nk0dt6

make sense ?

**Comment by theo4u** [comment]
@sanjayradadiya can . you share how you applied the `KeyHeaderParam` and also can you share your config `config/swaggergenerator.js` parameter field

**Comment by sanjayradadiya** [comment]
Hi @theo4u ,

This is my swagger generator 

```
module.exports["swagger-generator"] = {
    swaggerJsonPath: "./swagger/swagger.json",
    parameters: { //we can add up custom parameters here
        TokenHeaderParam: {
            in: 'header',
            name: 'token',
            required: false,
            type: 'string',
            description: 'Optional xsrf token which will be implanted at a later time'
        },
        KeyHeaderParam: {
          in: 'header',
          name: 'key',
          required: true,
          type: 'string',
          description: 'API key for identifications for each stores',
        },
    },
    blueprint_parameters: {
      list: [
        {
          $ref: '#/parameters/KeyHeaderParam'
        }
      ]
    },
    swagger: {
        swagger: '2.0',
        info: {
            title: 'test API documentation',
            version: '1.0.0'
        },
        externalDocs: {url: 'http://docs.swagger.api'},
        host: 'localhost:1337',
        basePath: '/',
    }
};

```
and applied in routes.js 

```
'GET /endpoint': {
    controller: 'controller',
    action: 'actionMethod',
    swagger: {
      query : [{
        $ref: '#/parameters/KeyHeaderParam'
      }],
      parameters: [
        {
          'in': 'query',
          'name': 'other',
          'required': true
        }
      ]
    }
  },
```

Thanks

**Comment by sanjayradadiya** [comment]
Can you update me for this issue i getting wrong params to generate if I am using this config?

https://prnt.sc/olaur4

**Comment by theo4u** [comment]
@sanjayradadiya you can check again, it should be fixed now

**Comment by theo4u** [comment]
https://github.com/theo4u/sails-hook-swagger-generator/releases/tag/v2.8.1

**Comment by sanjayradadiya** [comment]
I think I still have the issue because param is generated but it's not properly manner, showing [object object] in swagger.

![Screenshot at Aug 05 21-16-05](https://user-images.githubusercontent.com/16476120/62478646-3232a480-b7c9-11e9-858a-744528b76805.png)

![Screenshot at Aug 05 21-34-31](https://user-images.githubusercontent.com/16476120/62478660-38c11c00-b7c9-11e9-9b66-89e5516d84f8.png)

**Comment by theo4u** [comment]
So the current problem is just the description, lemme have a look

**Comment by theo4u** [comment]
@sanjayradadiya you can check again merged in https://github.com/theo4u/sails-hook-swagger-generator/releases/tag/v2.8.2

**Comment by sanjayradadiya** [comment]
Yes, Its looks good now, Thanks @theo4u
